"""add hashed_password

Revision ID: 0d8b8030dfe2
Revises: 6e5a7f0a23ce
Create Date: 2025-03-17 22:49:55.238335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8b8030dfe2'
down_revision: Union[str, None] = '6e5a7f0a23ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('hashed_password', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'hashed_password')
    # ### end Alembic commands ###
