"""unique

Revision ID: d1e9863502ee
Revises: 252b64136a93
Create Date: 2025-03-17 23:53:06.333044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e9863502ee'
down_revision: Union[str, None] = '252b64136a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_role', 'user_role', ['role', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_role', 'user_role', type_='unique')
    # ### end Alembic commands ###
